version: '3.4'
services:
  postgres:
    image: "postgres:15.2"
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    networks:
      my_network:
        ipv4_address: 10.5.0.5
  app:
    image: api_dime_track_image:latest
    entrypoint: "/app/docker-entrypoint.sh"
    ports:
      - 3086:3086
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/rails
      - ruby-bundle-cache:/bundle
    networks:
      my_network:
        ipv4_address: 10.5.0.6

  redis:
    image: "redis:7.0.11"
    ports:
      - 6379
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data
    networks:
      my_network:
        ipv4_address: 10.5.0.7

volumes:
  ruby-bundle-cache:
    external: true

networks:
  my_network:
    name: api_dime_track
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
