default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_dime_track_development

test:
  <<: *default
  database: api_dime_track_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:postgres, :database_name) %>
  username: <%= Rails.application.credentials.dig(:postgres, :user_name) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
