name: Deploy to Private Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Deploy to Private Server
        run: |
          ssh -o StrictHostKeyChecking=no vasyl@193.93.219.62 "cd ~/api_dime_track && make pull_build_run"

